config/routes.rb
Rails.application.routes.draw do
  resources :items, only: [:index, :show, :destroy]
  resources :merchants do
    resources :items, only: [:index, :new, :create, :edit, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :merchant
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  has_many :items, foreign_key: 'merchant_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    puts params[:merchant_id].present?
    if params[:merchant_id].present?
      @items = Item.where(merchant_id: params[:merchant_id])
    else
      @items = Item.all
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    respond_to do |format|

      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      @item = Item.find(params[:id])
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    if @item.present?
      @item.destroy
    end
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :price, :image, :active, :inventory).merge(merchant_id: params[:merchant_id])
    end
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  before_action :set_merchant, only: [:show, :edit, :update, :destroy]

  # GET /merchants
  # GET /merchants.json
  def index
    @merchants = Merchant.all
  end

  # GET /merchants/1
  # GET /merchants/1.json
  def show
    @merchant = Merchant.find(params[:id])
  end

  # GET /merchants/new
  def new
    @merchant = Merchant.new
  end

  # GET /merchants/1/edit
  def edit
  end

  # POST /merchants
  # POST /merchants.json
  def create
    @merchant = Merchant.new(merchant_params)

    respond_to do |format|
      if @merchant.save
        format.html { redirect_to @merchant, notice: 'Merchant was successfully created.' }
        format.json { render :show, status: :created, location: @merchant }
      else
        format.html { render :new }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /merchants/1
  # PATCH/PUT /merchants/1.json
  def update
    respond_to do |format|
      if @merchant.update(merchant_params)
        format.html { redirect_to @merchant, notice: 'Merchant was successfully updated.' }
        format.json { render :show, status: :ok, location: @merchant }
      else
        format.html { render :edit }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merchants/1
  # DELETE /merchants/1.json
  def destroy
    @merchant.destroy
    respond_to do |format|
      format.html { redirect_to merchants_url, notice: 'Merchant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merchant
      @merchant = Merchant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def merchant_params
      params.require(:merchant).permit(:name, :address, :city, :state, :zip)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, url: :merchant_items) do |form| %>
    <% puts :merchant_items %>
  <%= form.label :name %><br/>
  <%= form.text_field :name %>
  <%= form.label :description %><br/>
  <%= form.text_field :description %>
  <%= form.label :price %><br/>
  <%= form.text_field :price %>
  <%= form.label :image %><br/>
  <%= form.text_field :image %>
  <%= form.label :active %><br/>
  <%= form.text_field :active %>
  <%= form.label :inventory %><br/>
  <%= form.text_field :inventory %>

  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items&.each do |item| %>
      <tr>
        <td><%= "#{item.name}" %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_merchant_item_path(item.merchant, item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_merchant_item_path if params[:merchant_id] %>
<%= link_to 'Back', merchant_path(params[:merchant_id]) if params[:merchant_id] %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', merchant_items_path(params[:merchant_id]) %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>
<div class=<%= @item.active ? "active" : "inactive" %>>
  <h1><%= @item.name %></h1>
  <p>Description: <%= @item.description %></p>
  <p>Price: $<%= @item.price %></p>
  <p>Image (Pending): <%= @item.image %></p>
  <p>Quantity Remaining: <%= @item.inventory %></p>
  <p>Merchant: <%= link_to @item.merchant.name, merchant_path(@item.merchant) %></p>
</div>


<%= link_to 'Edit', edit_merchant_item_path(@item.merchant, @item) %>
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/merchants/_form.html.erb
<%= form_with(model: merchant, local: true) do |form| %>
  <%= form.label :name %><br/>
  <%= form.text_field :name %>

  <%= form.label :address %><br/>
  <%= form.text_field :address %>

  <%= form.label :city %><br/>
  <%= form.text_field :city %>

  <%= form.label :state %><br/>
  <%= form.text_field :state %>

  <%= form.label :zip %><br/>
  <%= form.text_field :zip %>

  <% if merchant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(merchant.errors.count, "error") %> prohibited this merchant from being saved:</h2>

      <ul>
        <% merchant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/merchants/edit.html.erb
<h1>Editing Merchant</h1>

<%= render 'form', merchant: @merchant %>

<%= link_to 'Show', @merchant %> |
<%= link_to 'Back', merchants_path %>

app/views/merchants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Merchants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @merchants.each do |merchant| %>
      <tr>
        <td><%= merchant.name %></td>
        <td><%= link_to 'Show', merchant %></td>
        <td><%= link_to 'Edit', edit_merchant_path(merchant) %></td>
        <td><%= link_to 'Destroy', merchant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Merchant', new_merchant_path %>

app/views/merchants/new.html.erb
<h1>New Merchant</h1>

<%= render 'form', merchant: @merchant %>

<%= link_to 'Back', merchants_path %>

app/views/merchants/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_merchant_path(@merchant) %> |
<%= link_to 'Back', merchants_path %>

<h1><%= @merchant.name %></h1>
<h3>Address Info</h3>
<p>Address: <%= @merchant.address %></p>
<p>City: <%= @merchant.city %></p>
<p>State: <%= @merchant.state %></p>
<p>Zip: <%= @merchant.zip %></p>


<p><%= link_to 'Items', merchant_items_path(@merchant) %></p>